name = "Fatherless Goes To Nature"
author = "Veonise"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00fa8546c9931088213d61066f3e06c9ba5e4f21b7c2235ad656b611715ac088"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
