name = "Fatherless Spooky Modpack"
author = "Veonise"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2de5ea49b6e28e61494e71ffa4f28147f9fc825ec95e7a97d00f8bae4654ac7c"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
