name = "Fatherless Goes To Nature"
author = "Veonise"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25197544810d28adc7f64a25cba2a6d4c5f8d9dcabc6989a09f7df8405b4a909"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
